apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptobot-data
  namespace: cryptobot
  labels:
    app.kubernetes.io/name: cryptobot
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
