[package]
name = "cryptobot-py"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cryptobot-core = { path = "../cryptobot-core", features = [] }
cryptobot-backtest = { path = "../cryptobot-backtest", features = [] }
cryptobot-features = { path = "../cryptobot-features", features = [] }
cryptobot-risk = { path = "../cryptobot-risk", features = [] }
cryptobot-stats = { path = "../cryptobot-stats", features = [] }
cryptobot-orderbook = { path = "../cryptobot-orderbook", features = [] }

[lib]
name = "cryptobot_py"
crate-type = ["cdylib"]

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }

[features]
default = []
python = ["cryptobot-core/python", "cryptobot-backtest/python", "cryptobot-features/python", "cryptobot-risk/python", "cryptobot-stats/python", "cryptobot-orderbook/python", "pyo3"]
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py38", "generate-abi3"], optional = true }